iOS 16.1 Live Activity support added
swift-server-community/APNSwift pull request #162
Opened 2022-09-21 04:34 UTC by nasircsms

2022-09-23 04:39 UTC, alex-de-waal commented
Thank you for this, you are a legend! 

How would I use the Activity's push token in the request's header? As described in the documentation:

> To use remote push notifications to update your Live Activities, you need to use push tokens for authenticating with APNs as described in [Establishing a Token-Based Connection to APNs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns).

> When you’ve successfully started your Live Activity, you receive an [Activity](https://developer.apple.com/documentation/activitykit/activity) with a [pushToken](https://developer.apple.com/documentation/activitykit/activity/pushtoken). Send it to your push notification server, and use it to send remote push notifications that update or end the Live Activity.

> Send push notifications to the Live Activity using the push token you stored on your server. It’s essential that you set the fields for the content-state key to match your custom [Activity.ContentState](https://developer.apple.com/documentation/activitykit/activity/contentstate-swift.typealias) type to ensure the system can decode the JSON payload and update the Live Activity.

2022-09-23 04:46 UTC, nasircsms commented
The deviceToken param will contain Activity pushToken. There is no need to send it separately. So we'll be sending push notification using Activity pushToken and deviceToken won't be required in this case. 
I should have updated param name to reflect this.

2022-09-23 04:52 UTC, alex-de-waal commented
Awesome, that helps a lot! Thanks again dude

2022-09-23 07:50 UTC, FranzBusch reviewed
Thanks for adding this just left a few comments that I spotted when comparing it to the Apple docs and the previous changes to the other APIs

2022-09-23 07:50 UTC, FranzBusch commented on Sources/APNSwift/LiveActivity/APNSClient+LiveActivity.swift
> +    /// Sends an alert notification to APNs.
This should probably be changed to say sending a live activity notification

2022-09-23 07:50 UTC, FranzBusch commented on Sources/APNSwift/APNSPushType.swift
> +    public static let liveactivity = Self(configuration: .liveactivity)
Taking from the Apple docs
```suggestion
    /// Use the live activity push type to update your live activity.
    ///
    /// - Important: If you set this push type, the topic must use your app’s bundle ID with `.push-type.liveactivity` appended to the end.
    public static let liveactivity = Self(configuration: .liveactivity)
```

2022-09-23 07:50 UTC, FranzBusch commented on Sources/APNSwift/LiveActivity/APNSClient+LiveActivity.swift
> +    ///    when registering for remote notifications.
This is not true according to the Apple docs
```suggestion
    ///   - deviceToken: The hexadecimal bytes that identify the user’s device. Your apps receives the bytes after you started the live activity.
    ///    when registering for remote notifications.
```

2022-09-23 07:50 UTC, FranzBusch commented on Sources/APNSwift/LiveActivity/APNSClient+LiveActivity.swift
> +            topic: notification.topic + ".push-type.liveactivity",
I think this is the wrong place to append this. Could you take a look at how the `APNSComplicationNotification` or `APNSLocationNotification` are doing it.

2022-09-23 07:50 UTC, FranzBusch commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotification.swift
> +//        try self.payload.encode(to: encoder)
This comment and code can be removed
```suggestion
```

2022-09-23 07:50 UTC, FranzBusch commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotificationAPSStorage.swift
> +public struct APNSLiveActivityNotificationAPSStorage<ContentState: Encodable>: Encodable {
This must not be public and all its members

2022-09-23 07:50 UTC, FranzBusch commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotification.swift
> +            contentState: contentState
We should expose these three properties as `public var` properties on this type as well to and add proper documentation.

2022-09-23 07:50 UTC, FranzBusch commented on Sources/APNSwift/LiveActivity/LiveActivityNotificationEvent.swift
> +public enum LiveActivityNotificationEvent: String {
This type need storage be public since we have to expose a var for users to set but we can't publicly expose an `enum` since we can't add new cases without breaking API. Please follow the approach that `APNSExpiration` or `APNSPriority` takes and use a `public struct` with an `internal enum` inside. Furthermore could you add some docs here please.

2022-09-24 17:50 UTC, frogg commented on Sources/APNSwift/LiveActivity/LiveActivityNotificationEvent.swift
> +public enum LiveActivityNotificationEvent: String {
LiveActivityNotificationEvent should also contain `end`

2022-09-26 06:28 UTC, nasircsms commented on Sources/APNSwift/LiveActivity/LiveActivityNotificationEvent.swift
> +public enum LiveActivityNotificationEvent: String {
Suggested changes are done.

2022-09-27 23:48 UTC, kylebrowning requested changes
Thanks so much, some more fixes here.

Along with 👇🏻 
- The topic property should include that the suffix is required same as the location notification does
- There are mentions of the `APNSAlertNotification` inside the new `APNSLiveActivityNotificaiton`

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSClient+LiveActivity.swift
> +//
In these 4 new files, please mimic/copy the other files with their licensed headers.

You will receive proper attribution via the contributors list

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSClient+LiveActivity.swift
> +        activityPushToken: String,
```suggestion
        deviceToken: String,
```

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSClient+LiveActivity.swift
> +        activityPushToken: String,
This should align with our other API's

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotification.swift
> +/// It is **important** that you do not encode anything with the key `aps`.
These are not necessary for this file
```suggestion
```

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotification.swift
> +    // Timestamp when sending notification
```suggestion
    /// Timestamp when sending notification
```

Is there anything else we can say about what this timestamp does?

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotification.swift
> +    // Event type e.g. update
```suggestion
    /// Event type e.g. update
```

I believe this could be elaborated on as well.

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotification.swift
> +    // Updated content-state of live activity
```suggestion
    /// The dynamic content of a Live Activity.
```

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotification.swift
> +        timestamp: Int
```suggestion
        expiration: APNSNotificationExpiration,
        priority: APNSPriority,
        appID: String,
        contentState: ContentState,
        event: LiveActivityNotificationEvent,
        timestamp: Int,
        apnsID: UUID? = nil,
```

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotification.swift
> +        timestamp: Int
apnsID should be last since it is optional

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/APNSLiveActivityNotificationAPSStorage.swift
> +import Foundation
```suggestion
```

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/LiveActivityNotificationEvent.swift
> +import Foundation
```suggestion
```

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/LiveActivityNotificationEvent.swift
> +public struct LiveActivityNotificationEvent: Hashable {
```suggestion
public struct APNSLiveActivityNotificationEvent: Hashable {
```

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/LiveActivityNotificationEvent.swift
> +    // Specifies that live activity should be updated
```suggestion
    /// Specifies that live activity should be updated
```

2022-09-27 23:48 UTC, kylebrowning commented on Sources/APNSwift/LiveActivity/LiveActivityNotificationEvent.swift
> +    // Specifies that live activity should be ended
```suggestion
    /// Specifies that live activity should be ended
```

2022-10-10 15:02 UTC, kylebrowning commented
@nasircsms planning n making these changes or should I take over?

2022-10-15 15:46 UTC, kylebrowning commented
closing in favor of #164

2022-10-15 15:46 UTC, closed without merging