Adjust to Swift 6 toolchain compile
swift-server-community/APNSwift pull request #202
Opened 2024-07-17 16:07 UTC by wangzhizhou

use the build command provided by Swift Package Index below to verify this package can be migrated to Swift 6 gracefully

```bash
env DEVELOPER_DIR=/Applications/Xcode-16.0.0-Beta.3.app xcrun swift build --arch arm64 -Xswiftc -strict-concurrency=complete
```

Reference this WWDC24 video to make change: https://developer.apple.com/wwdc24/10169

and the Guide to Migrate to Swift 6 on Swift Package Index: https://swiftpackageindex.com/ready-for-swift-6

If this PR is merged, after triggering the Swift Package Index build workflow, you can see the main branch be Safe from data race logo on the homepage of this package as below:

![image](https://github.com/user-attachments/assets/79a370c4-a07a-40ce-b377-63d64eccc6c1)

2024-07-17 16:12 UTC, 0xTim requested changes
Thanks! One change requested

2024-07-17 16:12 UTC, 0xTim commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
Unless we're going for a major version, this function should be annotated `@preconcurrency`

2024-07-17 16:14 UTC, wangzhizhou commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
OK, I will make this change as you described

2024-07-17 16:18 UTC, wangzhizhou commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
@0xTim After I have a try, this @preconcurrency attribute can not be added in this scene:

![image](https://github.com/user-attachments/assets/6e681e21-964e-4533-a700-468696e47f8f)

or 

![image](https://github.com/user-attachments/assets/895feaac-306d-4d8f-93be-7e1864d866e2)

2024-07-17 16:24 UTC, wangzhizhou commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
Are there any other suggestions for implementing this change?

2024-07-17 17:18 UTC, 0xTim commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
Sorry `@preconcurrency` goes before `func` - e.g. https://github.com/vapor/vapor/blob/main/Sources/Vapor/Utilities/Thread.swift#L5

2024-07-18 00:57 UTC, wangzhizhou commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
Ok，I have never used it before， may I have a try later.thanks Tim

2024-07-18 04:00 UTC, wangzhizhou commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
@0xTim I have add the @preconcurrency before the func shutdown

2024-07-18 10:02 UTC, merged