Updating project for stricture concurrency and Swift 6
swift-server-community/APNSwift pull request #207
Opened 2024-08-20 18:29 UTC by kylebrowning

2024-08-20 18:39 UTC, 0xTim commented on Sources/APNSCore/APNSClient.swift
> +    func shutdown(queue: DispatchQueue, callback: @Sendable @escaping (Error?) -> Void)
Why not make this async?

2024-08-20 18:39 UTC, 0xTim commented on Sources/APNSExample/Program.swift
> +import OSLog
Should we use SwiftLog here instead?

2024-08-20 18:39 UTC, 0xTim commented on Package.swift
> +// swift-tools-version:5.9
Assuming this is going into the major release why not 5.10 (or just 6.0 directly)

2024-08-20 18:39 UTC, 0xTim commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
See comment below, you could change this to

```swift
try await self.httpClient.shutdown()
```

This makes all the dispatch stuff an AHC problem

2024-08-20 18:57 UTC, kylebrowning commented on Sources/APNS/APNSClient.swift
> +    public func shutdown(queue: DispatchQueue = .global(), callback: @Sendable @escaping (Error?) -> Void) {
Got it, done

2024-08-20 18:58 UTC, kylebrowning commented on Package.swift
> +// swift-tools-version:5.9
Yeah, sure

2024-08-20 19:00 UTC, kylebrowning commented on Sources/APNSExample/Program.swift
> +import OSLog
Dusting off my chops sorry haah

2024-08-20 19:00 UTC, kylebrowning commented on Sources/APNSCore/APNSClient.swift
> +    func shutdown(queue: DispatchQueue, callback: @Sendable @escaping (Error?) -> Void)
DOne

2024-08-20 20:01 UTC, 0xTim requested changes

2024-08-20 20:01 UTC, 0xTim commented on Package.swift
> +              .enableExperimentalFeature("StrictConcurrency")
If you're going for a 6.0 manifest, then it's no longer an experimental feature. Best thing to do is set the language mode for the package like https://github.com/vapor/jwt-kit/blob/main/Package.swift#L43

2024-08-20 20:01 UTC, 0xTim commented on Sources/APNS/APNSClient.swift
> +        try await self.httpClient.shutdown()
Does this compile? It might need a `.get()` at the end

2024-08-20 20:01 UTC, 0xTim commented on Sources/APNSCore/APNSClient.swift
> +import Dispatch
No longer needed

2024-08-20 21:37 UTC, kylebrowning commented on Sources/APNS/APNSClient.swift
> +        try await self.httpClient.shutdown()
It does compile

2024-08-20 21:37 UTC, kylebrowning commented on Package.swift
> +              .enableExperimentalFeature("StrictConcurrency")
thx, done

2024-08-21 13:58 UTC, 0xTim requested changes
Couple of minor points

2024-08-21 13:58 UTC, 0xTim commented on Sources/APNS/APNSClient.swift
> +    /// Shuts down the client and event loop gracefully.
Nit - this doesn't touch the event loop

2024-08-21 13:58 UTC, 0xTim commented on Sources/APNSExample/Program.swift
> +let logger = Logger(label: "APNSwiftExample")
You have this logger and another one declared below

2024-08-21 14:13 UTC, kylebrowning commented on Sources/APNSExample/Program.swift
> +let logger = Logger(label: "APNSwiftExample")
Fixed! Thank

2024-08-21 14:14 UTC, 0xTim approved these changes
LGTM!

2024-08-21 14:33 UTC, merged